spring:
  application:
    name: service-management
  datasource:
    url: jdbc:mysql://127.0.0.1:5555/academy_ctrl?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: arthur
    password: arthur
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    timeout: 1000ms
  cache:
    redis:
      time-to-live: 1000ms
    type: redis
server:
  port: 21027

eureka:
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 10
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://118.126.113.248:21020/eureka/

logging:
  level:
    com.jnshu.management.dao: DEBUG
